name: localUnitTest
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: localUnitTest
    runs-on: ubuntu-latest
    steps:
      # コードのチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # JDKのセットアップ
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Gradleのキャッシュ復元
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # テスト実行
      - name: Test with Gradle
        run: ./gradlew test --stacktrace

      # テスト結果のアップロード
      - name: Upload test results Artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: results
          path: |
            **/build/reports/tests/**/*
            **/build/reports/test-results/**/*
          if-no-files-found: warn
          retention-days: 14